steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/crisislink','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/crisislink']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud','run','deploy','crisislink','--image=gcr.io/$PROJECT_ID/crisislink','--region=us-central1','--allow-unauthenticated','--memory=512Mi','--min-instances=1']
images: ['gcr.io/$PROJECT_ID/crisislink']
